config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/demos/', to: 'demos#index'
  post '/demos/addcart', to: 'demos#addcart'
  post '/demos/removecart', to: 'demos#removecart'
  post '/demos/clearcart', to: 'demos#clearcart'
  get '/demos/ajax', to: 'demos#ajax'

end

app/models/demo.rb
# == Schema Information
#
# Table name: demos
#
#  id                 :integer          not null, primary key
#  name               :string
#  title              :string
#  price              :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  prefecture_type_id :string
#  thumnail           :string
#
class Demo < ActiveRecord::Base
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture_type
  mount_uploader :thumnail, ThumnailUploader

  scope :cond_name, -> name { where(name: name) if name.present?}
  scope :cond_title, -> title { where(title: title) if title.present?}
  scope :cond_price, -> price { where(price: price) if price.present?}
  scope :cond_prefecture, -> prefecture_type_id {where(prefecture_type_id: prefecture_type_id) if prefecture_type_id.present?}
  def prefecture_type_name
    PrefectureType::NAME[self.prefecture_type_id]
  end

  def region_name(prefecture_type)
    RegionArea.where(code: prefecture_type[:region_code])[0]
  end

  def prefecture_type_name
    PrefectureType::NAME[self.prefecture_type_id]
  end

end

app/controllers/demos_controller.rb
class DemosController < InheritedResources::Base
  def index
    @front_search_condition = FrontSearchCondition.new(params)
    @items = ItemHeader.all
    @demos = Demo.cond_name(@front_search_condition.name).cond_title(@front_search_condition.title).cond_price(@front_search_condition.price).cond_prefecture(@front_search_condition.prefecture_type_id).page(params[:page]).decorate
  end

  def addcart
    itemheader = ItemHeader.where("shop_code = ? and item_code = ?", params[:shop_code], params[:item_code]).first
    cart_add(itemheader, 1)
    render :json => session[:cart]
  end

  def removecart
    cart_remove(params[:shop_code],params[:item_code])
    render :json => session[:cart]
  end

  def clearcart
    cart_clear
    render :json => session[:cart]
  end

  def ajax
    render :json => session[:cart]
  end

  private

end

app/helpers/demos_helper.rb
module DemosHelper
end

app/views/demos/_form.html.erb
<%= form_for(@demo) do |f| %>
  <% if @demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
      <% @demo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :prefecture %><br>
    <%= f.collection_select :prefecture_type_id, PrefectureType.all, :id, :name %>
  </div>
  <div class="field">
  <%= f.label :thumnail %>
　　<%= f.file_field :thumnail %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demos/edit.html.erb
<h1>Editing Demo</h1>

<%= render 'form' %>

<%= link_to 'Show', @demo %> |
<%= link_to 'Back', demos_path %>

app/views/demos/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_for @front_search_condition, as: :sc, url: '/demos', :method => :get do |f| %>
<li><%= f.text_field :name %></li>
<li><%= f.text_field :title %></li>
<li><%= f.text_field :price %></li>
<li><%= f.select(:prefecture_type_id, options_from_collection_for_select(@prefectures, :id, :name, @front_search_condition.prefecture_type_id.to_i), :include_blank => true) %></li>
<%= f.submit '検索' %>
<% end %>

<div id="testes">
  はっひふっへほー
</div>

<% @items.each do |item| %>
[<%= item.item_name %>]

<input type="button" value="追加" class="addcart" id="<%= item.shop_code %>_<%= item.item_code %>">
<input type="button" value="削除" class="removecart" id="<%= item.shop_code %>_<%= item.item_code %>">
<br/>
<% end %>
<input type="button" value="クリア" class="clearcart">
<br/>

<div id="cli">
  click&nbsp;click&nbsp;click
</div>
aaaaaaaaaaaa

<%= paginate @demos %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Price</th>
      <th>Prefecture</th>
      <th>Region</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @demos.each do |demo| %>
    <tr>
      <td><%= demo.name %></td>
      <td><%= demo.title %></td>
      <td><%= demo.format_price %></td>
      <td><%= demo.prefecture_type.name %></td>
      <td><%= demo.region_name(demo.prefecture_type).name %></td>
      <td><%= demo.thumnails %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/demos/new.html.erb
<h1>New Demo</h1>

<%= render 'form' %>

<%= link_to 'Back', demos_path %>

app/views/demos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @demo.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @demo.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @demo.price %>
</p>

<p>
  <strong>Prefecture:</strong>
  <%= @demo.prefecture_type.name %>
</p>

<p>
 <% if @demo.thumnail? %>
　　<%= image_tag @demo.thumnail.url %>
　<% else %>
　　<%= image_tag 'noimage.jpg' %>
　<% end %>
</p>


<%= link_to 'Edit', edit_demo_path(@demo) %> |
<%= link_to 'Back', demos_path %>

app/views/demos/timesupdate.js.erb
$("$result").html(
"<%= escape_javascript(render :partial => 'timesupdate' ) %>"
);
aiueo